apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jq0se0qgk-go 
  janus-idp.io/tekton: jq0se0qgk-go
  backstage.io/kubernetes-id: jq0se0qgk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jq0se0qgk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml