apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jq0se0qgk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jq0se0qgk-go 
  name: jq0se0qgk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jq0se0qgk-go 
